
import { ROLES } from './constants'

export const dummyUser = {
  id: '1',
  name: 'John Smith',
  email: 'john@vendocare.com',
  companyName: 'VendoCare Solutions',
  role: ROLES.ADMIN,
  avatar: null,
}


export const dummyUsersByRole = {
  [ROLES.ADMIN]: {
    id: '1',
    name: 'John Smith',
    email: 'admin@vendocare.com',
    companyName: 'VendoCare Solutions',
    role: ROLES.ADMIN,
    avatar: null,
  },
  [ROLES.FINANCE]: {
    id: '2',
    name: 'Sarah Johnson',
    email: 'finance@vendocare.com',
    companyName: 'VendoCare Solutions',
    role: ROLES.FINANCE,
    avatar: null,
  },
  [ROLES.VENDOR]: {
    id: '3',
    name: 'Mike Vendor',
    email: 'vendor@example.com',
    companyName: 'ABC Construction Ltd',
    role: ROLES.VENDOR,
    avatar: null,
  },
}

export const dummyVendors = [
  {
    id: '1',
    name: 'ABC Construction Ltd',
    email: 'contact@abcconstruction.com',
    phone: '+91 98765 43210',
    address: '123 Builder Street, Mumbai, India',
    rating: 4.8,
    category: 'Construction',
    status: 'Active',
    activeContracts: 3,
    totalSpent: 2500000,
    joinedDate: '2023-01-15',
  },
  {
    id: '2',
    name: 'Green Valley Landscaping',
    email: 'info@greenvalley.com',
    phone: '+91 98765 43211',
    address: '45 Garden Road, Delhi, India',
    rating: 4.5,
    category: 'Landscaping',
    status: 'Active',
    activeContracts: 2,
    totalSpent: 850000,
    joinedDate: '2023-03-20',
  },
  {
    id: '3',
    name: 'Smart Security Systems',
    email: 'sales@smartsecurity.com',
    phone: '+91 98765 43212',
    address: '78 Tech Park, Bangalore, India',
    rating: 4.9,
    category: 'Security',
    status: 'Active',
    activeContracts: 1,
    totalSpent: 1200000,
    joinedDate: '2023-06-10',
  },
  {
    id: '4',
    name: 'Elite Cleaning Services',
    email: 'bookings@elitecleaning.com',
    phone: '+91 98765 43213',
    address: '32 Service Lane, Chennai, India',
    rating: 4.2,
    category: 'Cleaning',
    status: 'Active',
    activeContracts: 2,
    totalSpent: 450000,
    joinedDate: '2023-08-05',
  },
  {
    id: '5',
    name: 'PowerMax Electricals',
    email: 'support@powermax.com',
    phone: '+91 98765 43214',
    address: '56 Electric Avenue, Hyderabad, India',
    rating: 4.6,
    category: 'Electrical',
    status: 'Inactive',
    activeContracts: 0,
    totalSpent: 680000,
    joinedDate: '2023-02-28',
  },
  {
    id: '6',
    name: 'AquaPure Plumbing',
    email: 'service@aquapure.com',
    phone: '+91 98765 43215',
    address: '89 Water Works, Pune, India',
    rating: 4.4,
    category: 'Plumbing',
    status: 'Active',
    activeContracts: 1,
    totalSpent: 320000,
    joinedDate: '2023-09-12',
  },
]

export const dummyContracts = [
  {
    id: '1',
    vendorId: '1',
    vendorName: 'ABC Construction Ltd',
    title: 'Annual Maintenance Contract',
    amount: 1500000,
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    paymentCycle: 'Quarterly',
    status: 'Active',
    description: 'Comprehensive annual maintenance for all construction needs',
  },
  {
    id: '2',
    vendorId: '1',
    vendorName: 'ABC Construction Ltd',
    title: 'Office Renovation Project',
    amount: 800000,
    startDate: '2024-03-01',
    endDate: '2024-06-30',
    paymentCycle: 'Monthly',
    status: 'Active',
    description: 'Complete office space renovation',
  },
  {
    id: '3',
    vendorId: '2',
    vendorName: 'Green Valley Landscaping',
    title: 'Garden Maintenance',
    amount: 300000,
    startDate: '2024-01-01',
    endDate: '2024-12-31',
    paymentCycle: 'Monthly',
    status: 'Active',
    description: 'Regular garden and landscape maintenance',
  },
  {
    id: '4',
    vendorId: '3',
    vendorName: 'Smart Security Systems',
    title: 'Security System Installation',
    amount: 1200000,
    startDate: '2023-10-01',
    endDate: '2024-09-30',
    paymentCycle: 'One-time',
    status: 'Expiring',
    description: 'CCTV and access control system installation',
  },
  {
    id: '5',
    vendorId: '4',
    vendorName: 'Elite Cleaning Services',
    title: 'Daily Cleaning Contract',
    amount: 240000,
    startDate: '2023-08-01',
    endDate: '2024-07-31',
    paymentCycle: 'Monthly',
    status: 'Expiring',
    description: 'Daily office cleaning services',
  },
  {
    id: '6',
    vendorId: '5',
    vendorName: 'PowerMax Electricals',
    title: 'Electrical Maintenance',
    amount: 500000,
    startDate: '2023-02-01',
    endDate: '2024-01-31',
    paymentCycle: 'Quarterly',
    status: 'Expired',
    description: 'Electrical system maintenance and repairs',
  },
]

export const dummyInvoices = [
  {
    id: '1',
    vendorId: '1',
    vendorName: 'ABC Construction Ltd',
    contractId: '1',
    invoiceNumber: 'INV-2024-001',
    amount: 375000,
    gstAmount: 67500,
    totalAmount: 442500,
    issueDate: '2024-01-05',
    dueDate: '2024-01-20',
    status: 'Paid',
    description: 'Q1 Maintenance Payment',
    fileUrl: null,
    paidDate: '2024-01-18',
    transactionId: 'TXN123456',
  },
  {
    id: '2',
    vendorId: '1',
    vendorName: 'ABC Construction Ltd',
    contractId: '2',
    invoiceNumber: 'INV-2024-002',
    amount: 200000,
    gstAmount: 36000,
    totalAmount: 236000,
    issueDate: '2024-03-05',
    dueDate: '2024-03-20',
    status: 'Paid',
    description: 'Renovation Project - Month 1',
    fileUrl: null,
    paidDate: '2024-03-15',
    transactionId: 'TXN123457',
  },
  {
    id: '3',
    vendorId: '2',
    vendorName: 'Green Valley Landscaping',
    contractId: '3',
    invoiceNumber: 'INV-2024-003',
    amount: 25000,
    gstAmount: 4500,
    totalAmount: 29500,
    issueDate: '2024-03-01',
    dueDate: '2024-03-15',
    status: 'Pending',
    description: 'March Maintenance',
    fileUrl: null,
    paidDate: null,
    transactionId: null,
  },
  {
    id: '4',
    vendorId: '3',
    vendorName: 'Smart Security Systems',
    contractId: '4',
    invoiceNumber: 'INV-2024-004',
    amount: 600000,
    gstAmount: 108000,
    totalAmount: 708000,
    issueDate: '2024-02-15',
    dueDate: '2024-03-01',
    status: 'Overdue',
    description: 'Security System - Phase 1',
    fileUrl: null,
    paidDate: null,
    transactionId: null,
  },
  {
    id: '5',
    vendorId: '4',
    vendorName: 'Elite Cleaning Services',
    contractId: '5',
    invoiceNumber: 'INV-2024-005',
    amount: 20000,
    gstAmount: 3600,
    totalAmount: 23600,
    issueDate: '2024-03-01',
    dueDate: '2024-03-10',
    status: 'Pending',
    description: 'February Cleaning Services',
    fileUrl: null,
    paidDate: null,
    transactionId: null,
  },
  {
    id: '6',
    vendorId: '6',
    vendorName: 'AquaPure Plumbing',
    contractId: '6',
    invoiceNumber: 'INV-2024-006',
    amount: 80000,
    gstAmount: 14400,
    totalAmount: 94400,
    issueDate: '2024-02-20',
    dueDate: '2024-03-05',
    status: 'Overdue',
    description: 'Emergency Plumbing Repairs',
    fileUrl: null,
    paidDate: null,
    transactionId: null,
  },
]

export const dummyPayments = [
  {
    id: '1',
    invoiceId: '1',
    vendorName: 'ABC Construction Ltd',
    amount: 442500,
    paymentDate: '2024-01-18',
    transactionId: 'TXN123456',
    method: 'Bank Transfer',
    status: 'Completed',
  },
  {
    id: '2',
    invoiceId: '2',
    vendorName: 'ABC Construction Ltd',
    amount: 236000,
    paymentDate: '2024-03-15',
    transactionId: 'TXN123457',
    method: 'Bank Transfer',
    status: 'Completed',
  },
  {
    id: '3',
    invoiceId: '7',
    vendorName: 'Green Valley Landscaping',
    amount: 29500,
    paymentDate: '2024-02-15',
    transactionId: 'TXN123458',
    method: 'UPI',
    status: 'Completed',
  },
]

export const dummyReports = {
  monthlySpending: [
    { month: 'Jan 2024', amount: 442500, vendorCount: 2 },
    { month: 'Feb 2024', amount: 29500, vendorCount: 1 },
    { month: 'Mar 2024', amount: 259500, vendorCount: 3 },
  ],
  overdueInvoices: [
    { id: '4', vendorName: 'Smart Security Systems', amount: 708000, daysOverdue: 15 },
    { id: '6', vendorName: 'AquaPure Plumbing', amount: 94400, daysOverdue: 10 },
  ],
  taxSummary: {
    totalGst: 127000,
    totalAmount: 1754400,
    gstBreakdown: [
      { rate: '18%', amount: 127000, taxableValue: 705000 },
    ],
  },
}

export const dummyStats = {
  totalVendors: 6,
  activeContracts: 5,
  pendingInvoices: 2,
  outstandingAmount: 802400,
  totalSpent: 731500,
  overdueAmount: 802400,
}
